version: '3.8'

services:
  frontend:
    build: ./client
    ports:
     - "80:80"
    depends_on:
     - backend  

  backend:
    build: ./server
    ports:
     - "5000:3000"
    environment:
     - PORT=3000
     - DATABASE_URL=${DATABASE_URL}   
     - DIRECT_URL=${DIRECT_URL}     
     - REDIS_URL=redis://redis:6379
   
    depends_on:
     - redis


  redis:
    image: redis:7-alpine
    ports:
     - "6379:6379"
